# based on the Syncthing documentation: https://github.com/syncthing/syncthing/blob/main/README-Docker.md
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing-ec2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/st-sync:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped